### ISSUE TITLE
How to connect to local

### ISSUE THREAD

**Issue by saintplay** [galexrt/go-rcon#1]
Hello,
I’m trying to connect to send commands to my own server, I’ve tried putting “localhost”, “127.0.0.1”, “0.0.0.0” but neither of those works.

**Comment by galexrt** [comment]
Gameserver normally don't run on `127.0.0.1` / localhost.
Check on which IP address the gameserver is actually listening to be able to connect to it.
E.g., under linux `netstat -tulpn` and / or `ss -tulpn`.

***

Closing as not a bug.
